org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.22)
neo_version=21.1.77
neo_version_range=[21.1.0,)
loader_version_range=[4,)

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

mod_id=animania
mod_name=Animania
mod_license=Animania License
mod_version=3.0.0
mod_group_id=com.animania
mod_authors=Purplicious_Cow, RazzleberryFox, ...
mod_description=Animania is an immersive mod that replaces and improves the passive animals in Minecraft. Unofficial port to NeoForge 1.21.1.
